# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Install Dependencies
        run: npm ci
      - name: Run build
        run: DB_PATH=./db/game.sqlite npm run build
      - name: Run tests
        run: npm run test
